config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  
  root 'tasks#index'

end

app/models/task.rb
class Task < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :all_tasks, only: [:index, :create, :update, :destroy]
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # index and show actions removed
  def destroy
  @task.destroy
  end
  
  def update
     @task.update(task_params) 
  end  
    
  def new
    @task = Task.new
  end

  def create
    #@task = Task.new(task_params)
    @task  = Task.create(task_params)
  end

  private

    # new action
    def all_tasks
      @tasks = Task.all
    end

    def set_task
      @task = Task.find(params[:id])
    end

    def task_params
      params.require(:task).permit(:description, :deadline)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<body>
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
    <%= yield %>
    </div>
  </div>

</body>
</html>

app/views/tasks/_form.html.erb
<%= simple_form_for @task, remote: true do |f| %>
  <%= f.text_area :description, placeholder: "Describe your task!"%>
  <br>
  
  <%= f.text_field :deadline, id: "datetimepicker1", placeholder: "When is it due?" %>
  <br>
  <%= f.button :submit%>
<% end %> 

app/views/tasks/_task.html.erb
<li>
  <%= task.description %>
  <%= task.deadline %>
  <%= link_to "Edit", edit_task_path(task), remote: true %>
  <%= link_to "Delete", task, remote: true, method: :delete, data: {confirm: "Are you sure?"} %>
</li>

app/views/tasks/create.js.erb
$('#task').html("<%= j render @tasks %>");
$('#task-form').slideDown(350);

app/views/tasks/destroy.js.erb
('#tasks').html("<%= j render @tasks %>");

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/edit.js.erb
$('#task-form').html("<%= j render 'form' %>");
$('#task-form').slideDown(350);

<%=render 'datetimepicker' %>

app/views/tasks/index.html.erb
<h1>Listing tasks</h1>
<%= link_to 'New Task', new_task_path, remote: true %>

<div id="task-form" style="display:none;"></div>  

<h2>Tasks</h2>
<div id="tasks">
  <ul>
    <%= render @tasks %>
  </ul>
</div>
<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Deadline</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.description %></td>
        <td><%= task.deadline %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_task_path, remote: true %>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/new.js.erb
$('#task-form').html("<%= j render 'form' %>");
$('#task-form').slideDown(350);

<%= render 'datetimepicker' %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @task.description %>
</p>

<p>
  <strong>Deadline:</strong>
  <%= @task.deadline %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/update.js.erb
$('#task').html("<%= j render @tasks %>");
$('#task-form').slideDown(350);